2023-08-27 19:26:22,654 [INFO] root tankworker.py:153	Log file created
2023-08-27 19:26:22,655 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2023-08-27 19:26:22,656 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2023-08-27 19:26:22,657 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2023-08-27 19:26:22,686 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2023-08-27_19-26-22.511311
2023-08-27 19:26:22,691 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2023-08-27 19:26:22,692 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2023-08-27 19:26:22,693 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2023-08-27 19:26:22,693 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2023-08-27 19:26:22,694 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2023-08-27 19:26:22,695 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2023-08-27 19:26:22,696 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2023-08-27 19:26:22,696 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2023-08-27 19:26:22,709 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2023-08-27 19:26:22,710 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2023-08-27 19:26:22,711 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2023-08-27 19:26:22,711 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2023-08-27 19:26:22,712 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2023-08-27 19:26:22,713 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2023-08-27 19:26:22,714 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2023-08-27 19:26:22,714 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2023-08-27 19:26:22,715 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2023-08-27 19:26:22,716 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2023-08-27 19:26:22,746 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.2 and port 80
2023-08-27 19:26:22,753 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.2]:80
2023-08-27 19:26:22,754 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.2 and port 80
2023-08-27 19:26:22,757 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.2]:80
2023-08-27 19:26:22,758 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.2 and port 80
2023-08-27 19:26:22,760 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.2]:80
2023-08-27 19:26:22,764 [ERROR] yandextank.common.util util.py:815	Exception occurred:
<class 'RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankworker.py", line 70, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankcore.py", line 262, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 67, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 76, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 274, in read_config
    self.ipv6, self.resolved_ip, self.port, self.address = self.address_wizard.resolve(

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 587, in resolve
    raise RuntimeError(msg % address_str)

2023-08-27 19:26:22,765 [INFO] yandextank.common.util util.py:816	Trying to clean up
2023-08-27 19:26:22,766 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_k1zzhew8.lock
2023-08-27 19:26:22,786 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2023-08-27_19-26-22.511311
2023-08-27 19:26:22,787 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2023-08-27 19:26:22,788 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-26-22.511311/answ_b59rx78w.log
2023-08-27 19:26:22,789 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-26-22.511311/phout_nvbl1jbt.log
2023-08-27 19:26:22,790 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-26-22.511311/phantom_stat_hfcteed0.log
2023-08-27 19:26:22,791 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2023-08-27_19-26-22.511311/phantom_jjlrjhhe.log
